{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "greenroute.fullname" . }}
  labels:
    {{- include "greenroute.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  selector:
    matchLabels:
      {{- include "greenroute.selectorLabels" . | nindent 6 }}
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [edge-api, routing-orchestrator, provider-yandex]
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      honorLabels: false
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
          targetLabel: service
{{- end }}
